SQL Project
==========

--------------------------------------------------------
--  File created - Friday-July-04-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJECT"."USERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."COURSE" 
   (	"C_ID" VARCHAR2(20 BYTE), 
	"C_NAME" VARCHAR2(20 BYTE), 
	"I_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "PROJECT"."INSTRUCTOR" 
   (	"I_ID" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARKS
--------------------------------------------------------

  CREATE TABLE "PROJECT"."MARKS" 
   (	"S_ID" VARCHAR2(20 BYTE), 
	"C_ID" VARCHAR2(20 BYTE), 
	"MARKS" NUMBER(2,3)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "PROJECT"."STUDENTS" 
   (	"S_ID" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" NUMBER, 
	"ADDRESS" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PROJECT"."USERS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"U_ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"PRIVILEGE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PROJECT.COURSE
SET DEFINE OFF;
Insert into PROJECT.COURSE (C_ID,C_NAME,I_ID) values ('C001','MUSIC','I001');
REM INSERTING into PROJECT.INSTRUCTOR
SET DEFINE OFF;
Insert into PROJECT.INSTRUCTOR (I_ID,FNAME,LNAME,EMAIL,PHONE) values ('I001','MATHEWS','JOHN','JOHNMATHEWS@OXFORD.COM',123456789);
REM INSERTING into PROJECT.MARKS
SET DEFINE OFF;
REM INSERTING into PROJECT.STUDENTS
SET DEFINE OFF;
Insert into PROJECT.STUDENTS (S_ID,FNAME,LNAME,EMAIL,PHONE,ADDRESS) values ('S001','EDWARD','SNOWDEN','EDWARDSNOWDEN@NSA.COM',987654321,'456 WHITE HOUSE');
REM INSERTING into PROJECT.USERS
SET DEFINE OFF;
Insert into PROJECT.USERS (ID,U_ID,PW,PRIVILEGE) values ('3','ADMIN','password',1);
Insert into PROJECT.USERS (ID,U_ID,PW,PRIVILEGE) values ('4','I001','paaword',2);
Insert into PROJECT.USERS (ID,U_ID,PW,PRIVILEGE) values ('5','S001','password',3);
--------------------------------------------------------
--  DDL for Index STEUDENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."STEUDENTS_PK" ON "PROJECT"."STUDENTS" ("S_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."USERS_PK" ON "PROJECT"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."MARKS_PK" ON "PROJECT"."MARKS" ("S_ID", "C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSTRUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."INSTRUCTOR_PK" ON "PROJECT"."INSTRUCTOR" ("I_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."COURSE_PK" ON "PROJECT"."COURSE" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARKS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."MARKS_UK1" ON "PROJECT"."MARKS" ("S_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MARKS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MARKS" ADD CONSTRAINT "MARKS_PK" PRIMARY KEY ("S_ID", "C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT"."MARKS" ADD CONSTRAINT "MARKS_UK1" UNIQUE ("S_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT"."MARKS" MODIFY ("S_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT"."MARKS" MODIFY ("C_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."STUDENTS" ADD CONSTRAINT "STEUDENTS_PK" PRIMARY KEY ("S_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT"."STUDENTS" MODIFY ("S_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "PROJECT"."INSTRUCTOR" ADD CONSTRAINT "INSTRUCTOR_PK" PRIMARY KEY ("I_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT"."INSTRUCTOR" MODIFY ("I_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT"."INSTRUCTOR" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."USERS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT"."USERS" MODIFY ("U_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT"."USERS" MODIFY ("PRIVILEGE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT"."COURSE" MODIFY ("C_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT"."COURSE" MODIFY ("I_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."COURSE" ADD CONSTRAINT "COURSE_FK" FOREIGN KEY ("I_ID")
	  REFERENCES "PROJECT"."INSTRUCTOR" ("I_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARKS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."MARKS" ADD CONSTRAINT "MARKS_FK" FOREIGN KEY ("S_ID")
	  REFERENCES "PROJECT"."STUDENTS" ("S_ID") ENABLE;
 
  ALTER TABLE "PROJECT"."MARKS" ADD CONSTRAINT "MARKS_FK2" FOREIGN KEY ("C_ID")
	  REFERENCES "PROJECT"."COURSE" ("C_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_USERS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROJECT"."BI_USERS" 
  before insert on "USERS"               
  for each row  
begin   
    select "USERS_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER "PROJECT"."BI_USERS" ENABLE;
